### ISSUE TITLE
image-loader doesn't work with WkWebView 

### ISSUE THREAD

**Issue by mmirzaee** [zyramedia/ionic-image-loader#11]
Hi, 
Everything worked great before using WkWebView for my ios application [https://github.com/apache/cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine)

I'm confused, because on simulator everything is ok too !! and no errors on debugging can be found.
on production and after installing on real devices images do not load.

can you help please ?

**Comment by ihadeed** [comment]
Hey there,

WkWebView doesn't allow access to anything outside the www root directory. This module stores the cached images outside the www directory (in the app's cache directory). 

I'm thinking to solve this issue I can add a fallback for WkWebView and return base64 data instead of a file URI.

**Comment by mmirzaee** [comment]
Thank you man ,
I really appreciate it, if there could be hot fix for this.

**Comment by mmirzaee** [comment]
As you mentioned WkWebView doesn't allow access to anything outside the www! so I tried to set _cacheDirectoryName to www/cache and it worked for me.

Thank you

**Comment by ihadeed** [comment]
@mmirzaee did you do that through `ImageLoaderConfig` ? 

When I looked into this I remember finding out that the cordova-plugin-file cannot write to the www directory (see here: https://github.com/apache/cordova-plugin-file#ios-file-system-layout). That directory is read-only on iOS platform. How did you manage to write files to it?

**Comment by mmirzaee** [comment]
honestly I don't know much about cordova-plugin-file, I just updated 'image-loader-config.js' , line13 to:
`this._cacheDirectoryName = 'www/cache';`
and then it worked like a charm :)

**Comment by ihadeed** [comment]
@mmirzaee yeah that's the same as injecting `ImageLoaderConfig` and calling `setCacheDirectoryName`. This is strange because it's still being saved under the cache directory. (see https://github.com/zyramedia/ionic-image-loader/blob/master/src/providers/image-loader.ts#L188).

Thanks for the update though, I will keep this mind in case others have the same issue.

**Comment by mmirzaee** [comment]
I tried using other dir names ( like 'cache','www2/cache') to find out why it's really working! 
the cool fact was that 'www' must be in cache path ! maybe it's a bug of wkwebview ! ( I really dont know ) 

`
this._cacheDirectoryName = 'www/cache'; // works fine
this._cacheDirectoryName = 'www'; // works fine
this._cacheDirectoryName = 'www2'; // doesn't work
this._cacheDirectoryName = 'anythingelse'; //doesn't work
`

**Comment by ihadeed** [comment]
@mmirzaee that's good to know. Thanks for the update!

**Comment by kshaaban-** [comment]
Unfortunately that didn't solve it for me
Using `setCacheDirectoryName` is just setting the directory within the Librarycache folder

What @mmirzaee faced was probably the images loading/showing initially (as they're loaded from url) but on a page reload/refresh, WkWebView will still fail to load locally cached files.
