### ISSUE TITLE
Doesnt work after update to version 1.3.0

### ISSUE THREAD

**Issue by mmirzaee** [zyramedia/ionic-image-loader#13]
Hi, 
For some reason images don't load from cache after I updated to version 1.3.0 and always images start to load from internet!
reverted to 1.2.0 and everything works fine again ! 
I didn't set any custom configuration and I'm not using WKWebView in my project.

Thank you

**Comment by XPanniX** [comment]
I'm running version 1.3.0 as well and for me everything works fine if my app runs on a(n) (android) device.
In browser the images are not cached (not sure if this is the desired behaviour).

**Comment by ihadeed** [comment]
There were no changes in 1.3.0 that could have affected the caching functionality. You must be facing a different issue.

See https://github.com/zyramedia/ionic-image-loader/compare/v1.2.0...v1.3.0

**Comment by ihadeed** [comment]
Correction: I am able to reproduce this issue now and it is caused by the `1.3.0` update.  The error message is `TypeError: Cannot read property 'platform' of undefined(…)` and it is caused by the call made to the `device` plugin.  It's supposed to be `device` and not `cordova.device`.
