### ISSUE TITLE
Idea: Maximum Cache Size

### ISSUE THREAD

**Issue by XPanniX** [zyramedia/ionic-image-loader#14]
First of all great work on this module, I really like it and it saved me a lot of work!

What came in to my mind is a feature to define a maximum size for the cache. 
If you want to cache a new image and the cache limit is reached the oldest or marked as less relevant entries would be removed from cache to free space for the new image.

Since I want to cache quite a few images the cache size would increase pretty fast and I don't wont to flood the users phone storage with a bunch of cached images.

**Comment by ihadeed** [comment]
This is a great idea. Thanks for the suggestion.

I will work on adding it when I get a chance. I will probably also add an option to set maximum cache lifetime, this will automatically delete cached files older than X days.

**Comment by XPanniX** [comment]
Looking at the `config.ts` I found
```TypeScript
maxCacheSize: number = -1;

maxCacheAge: number = -1;
```
So I suppose these features are disabled by default?

Would be nice to have that pointed out in the readme

**Comment by ihadeed** [comment]
@XPanniX Yes they're disabled by default. I will leave a note in the readme now.
