### ISSUE TITLE
Feature Request: preload Method

### ISSUE THREAD

**Issue by Bastl34** [zyramedia/ionic-image-loader#16]
It would be great to have a `preload(url)` on the imageLoader Service to allow to cache an image before a view with `<img-loader src="MYURL"></img-loader>` was rendered. This would be good to preload images if you are offline.

**Comment by ihadeed** [comment]
Great idea, will add it when I get a chance.

**Comment by ihadeed** [comment]
You can use `ImageLoader.getImage(..)` to do this, but I just added a `preload` method so it's more clear. Will be available soon in `v1.4.0`
