### ISSUE TITLE
Typescript error when building the app

### ISSUE THREAD

**Issue by abenetashagre** [zyramedia/ionic-image-loader#2]
I get this errors when I build the app. 

TypeScript error: node_modules/ionic-image-loader/dist/providers/image-loader.d.ts(13,22): Error TS1005: '=' expected.
TypeScript error: node_modules/ionic-image-loader/dist/providers/image-loader.d.ts(14,22): Error TS1005: '=' expected.

My TypeScript version is 2.0.3

How can I solve this?

**Comment by ihadeed** [comment]
Not sure why you're getting that error. Can you try to run `npm i --save ionic-image-loader@latest` just to make sure you got the latest files. 

Lines 13 and 14 of `image-loader.d.ts` are as follows:
```
    private readonly filePluginExists;
    private readonly cacheDirectoryExists;
```

It's a declaration file, it shouldn't have any `=` signs.
