### ISSUE TITLE
Loading spinner never leaves 

### ISSUE THREAD

**Issue by cubissimo** [zyramedia/ionic-image-loader#20]
Loading spinner is not hiding after img loaded.

Also, spinner parameters is not working too

**Comment by ihadeed** [comment]
Could you please share your code with me so I can try to reproduce this? Also, what do you mean by "spinner parameters is not working" ? what parameters?

**Comment by cubissimo** [comment]
i mean the using of the attribute spinner="false" do not work and 
`imageLoaderConfig.enableSpinner(false);` not working too;

i'll try to reproduce in a fresh project to share with u, i'll back soon.

tks

**Comment by tabirkeland** [comment]
@cubissimo please try using the `spinner`attribute like this in your markup:

```html
<img-loader src="{{ speaker.headshot }}" useImg [spinner]="false"></img-loader>
```

**Comment by cubissimo** [comment]
@tabirkeland I can confirm now! It's work!

I end up handling a spinner outside img-loader, encapsulating in a custom element.

Is there a some kind of output `OnLoad` event to listen?

If not can i open a feature request?

**Comment by tabirkeland** [comment]
@cubissimo not tested but you should be able to do something like so:

```html
<img-loader src="{{ speaker.headshot }}" useImg [spinner]="false" (load)="imageLoaded()"></img-loader>
```

and then in your page controller:

```typescript
export class MyExamplePage
{
    public imageLoaded() {
      // do something
   }  
}
```

**Comment by cubissimo** [comment]
Perfect! i was checked the source code looking for this but missed! sry!

Tks! I'm closing this issue
