### ISSUE TITLE
'img-loader' is not a know element

### ISSUE THREAD

**Issue by felipefda** [zyramedia/ionic-image-loader#21]
Hello guys,

I follow every step of installation for this plugin but when I switch <img> tag to <img-loader> i have this error:
'img-loader' is not a known element:

Anyone can tell me what i did wrong?

**Comment by ihadeed** [comment]
You might have missed the step where you include `ImageLoaderModule` into your `NgModule`.

**Comment by felipefda** [comment]
Thanks. There was an error exactly in this file. All working now.
Excellent job.

**Comment by pcsantana** [comment]
Hi!
I was facing the same problem. 
I figure out the example app is a little different than the README section.

In the README, in installation section [number 3](https://github.com/zyra/ionic-image-loader#3-import-ionicimageloader-module) tells to use **imports**:

```javascript
import { IonicImageLoader } from 'ionic-image-loader';

@NgModule({
  ...
  imports: [IonicImageLoader]
})
export class SharedModule {}
```

But in the example app (the correct way) use **exports**:
```javascript
import { IonicImageLoader } from 'ionic-image-loader';

@NgModule({
  ...
  exports: [IonicImageLoader]
})
export class SharedModule {}
```

Please update the README.
Thank you for this awesome plugin.

**Comment by xProgrammer-007** [comment]
Remember , simply importing `IonicImageLoader` in child module wont help , You need to export the Module and then import it back in child module . Shared module will help , follow the docs 
Shared module is best option for lazy loading.
