### ISSUE TITLE
Not working with WKWebView

### ISSUE THREAD

**Issue by askona** [zyramedia/ionic-image-loader#22]
HI! Plugin works incorrect when running on WKWebView, because of this condition
`if (window.location.protocol === 'http:' || window.location.protocol === 'https:')`
it detects app as running in browser. It would be great to make this condition more correct

**Comment by ihadeed** [comment]
@askona are you running on `livereload`?

**Comment by askona** [comment]
No, im not using livereload. Also, even with check above omitted, i have error
`Not allowed to load local resource: file:///Users/admin/Library/Developer/CoreSimulator/Devices/471F448D-7CD6-4BBE-A9AC-56F27EFA934B/data/Containers/Data/Application/2459D1C3-4321-4D40-AFB6-52EA12C46A01/Library/Caches/image-loader-cache/1289029802`
Maybe it's more related to WKWebView, just to let you know this problem

**Comment by ihadeed** [comment]
What version of `ionic-image-loader` are you using? WKWebView support was only added in 1.3.0

**Comment by askona** [comment]
I'm using 1.6.0

**Comment by askona** [comment]
Hello again, i found what's the problem. Check for the [pull request](https://github.com/zyramedia/ionic-image-loader/pull/25)

**Comment by askona** [comment]
![image](https://cloud.githubusercontent.com/assets/12323173/23267664/18d1b3c2-f9f4-11e6-8b9b-a3769a2e550a.png)

**Comment by ihadeed** [comment]
@askona by `livereload` I meant `ionic run ios --livereload`. But I see you're not using that.

The WKWebView support that we currently have is for regular WKWebView, not the one modified by Ionic with the fix you linked to earlier.

I will review the PR you submitted and make sure it works for all cases, and then I'll merge.

**Comment by ihadeed** [comment]
Merged the PR and now is available in version `1.7.2`
