### ISSUE TITLE
Feature Request: Allow a pre-packaged image cache to be shipped with the App

### ISSUE THREAD

**Issue by wundo** [zyramedia/ionic-image-loader#26]
It would be great if this package allowed to us to ship the binary with a pre-populated set of cached images (similar to what is done by [litehelpers/Cordova-sqlite-ext](https://github.com/litehelpers/Cordova-sqlite-ext)) this way we could avoid wasting network resources in the device.

**Comment by ihadeed** [comment]
How would this be different than loading local resources? (using local image URL rather than remote)
