### ISSUE TITLE
Images not loading on first time loading the page

### ISSUE THREAD

**Issue by alexrindone** [zyramedia/ionic-image-loader#27]
I tested this on an iPhone 6, with ios 10.2. Images are only loading after a page has been refreshed. They aren't loading on the first load of the page. The only way I could get them to load was if I closed the page within my app and then opened it again.

**Comment by ihadeed** [comment]
@alexrindone I just tested it on iOS 10.2 simulator. I'm unable to reproduce this issue.

You might have some problems with your Ionic app. I recently experienced some NgZone issues as well.

I did the test using the [example project](https://github.com/zyramedia/ionic-image-loader-example).

**Comment by jonasschumacher** [comment]
I was experiencing the same problem with android. I had a look at your example project and found that I need to set the MaximumCacheSize, otherwise it doesn't return the downloaded picture in the first load, and the spinner keeps spinning forever.

I hope that helped.

**Comment by highjump0615** [comment]
@jonasschumacher  I am building app with this plugin and getting same problem as you. The images are not shown for the first time, and when you quite app and restart, they are being shown.. I tried with initializing MaximumCacheSize, but no effects and spinner keeps spinning forever... :(

**Comment by jonasschumacher** [comment]
@highjump0615 Sorry for the delay... I've updated my project and it's still working. 
Can you share some code? Maybe I can figure it out.
