### ISSUE TITLE
"Attempted to assign readonly property" on iOS

### ISSUE THREAD

**Issue by XPanniX** [zyramedia/ionic-image-loader#28]
I'm not entirely sure if it's caused by your module but since only images aren't displayed I suppose it has to do something with it:  
When running on iOS I get the following error:
```
handleError — error_handler.js:47EXCEPTION: Error in ./HomePage class HomePage - inline template:22:36 caused by: Attempted to assign to readonly property.
handleError — error_handler.js:49ORIGINAL EXCEPTION: Attempted to assign to readonly property.
```
On my HomePage Template file on line 22:36 is the code to set the img-loader src like this:
```html
<img-loader [src]="event.cover.source" backgroundSize="cover" [style]="event.cover.style"></img-loader>
```

In the app it looks like this:
![image](https://cloud.githubusercontent.com/assets/1346944/23511292/e58f740e-ff5c-11e6-9ab1-7ce24191647e.png)
The white boxes should be two full width images

**Comment by ihadeed** [comment]
Can you share code to reproduce this? both HTML and TS.

**Comment by XPanniX** [comment]
I created this Repo which does what my App does a little simplified, since my data comes from an API:
https://github.com/XPanniX/ImageLoaderBug

Basically it's just getting URLs to images from the API and then for each URL creating a new `img-loader` with the `[src]` attribute set to the URL

**Comment by ihadeed** [comment]
@XPanniX Just tested out that repo, I'm unable to reproduce the issue you've mentioned. 

- Cloned repo
- installed `file` and `file-transfer` plugins
- ran `ionic run ios`
