### ISSUE TITLE
Ionic Native 3.x

### ISSUE THREAD

**Issue by claudiozam** [zyramedia/ionic-image-loader#30]
Hi, thanks for your excellent plugin and your effort.
Are you going to add support to Ionic Native 3.X?

Thanks!!

**Comment by ihadeed** [comment]
@claudiozam 
Hey there,

I will publish an update soon that uses Ionic Native 3.x

**Comment by ihadeed** [comment]
Just published `ionic-image-loader@2.0.2` that uses Ionic Native 3.x
