### ISSUE TITLE
Usage with Firebase Storage

### ISSUE THREAD

**Issue by dmastag** [zyramedia/ionic-image-loader#4]
When trying to use this with images stored in Firebase Storage I am getting this returned:

```
{
  "error": {
    "code": 403,
    "message": "Permission denied. Could not perform this operation"
  }
}
```

Though, if I access the url directly that is indeed what I am getting.
Asking if there is a possibility to use this plugin with images that keep a session?

**Comment by ihadeed** [comment]
Is there a special header that must be sent in order to pull files from your Firebase storage?

**Comment by dmastag** [comment]
I am actually not sure.
Was thinking to modify the plugin to pull the image from the img directly using canvas, do you think that would be possible?

**Comment by ihadeed** [comment]
@dmastag Can you show me how do you usually load your images from firebase?

**Comment by uzumakinaruto123** [comment]
@ihadeed  great plugin ! I am using firbase too. there was no permission issue with my firbase database.

But it throws error `main.js:19 GET file:///android_asset/www/taken net::ERR_FILE_NOT_FOUND`

On inspection , I found it was using this url

`file:///data/user/0/com.ionic.test/cache/ioniccache/63212651`

I checked the cache directory(I have root access) , file named `63212651` was present in that directory.

So , it was giving file not found error if file was present.


**Additionaly ,**
(I don't if I should make separate issue for this)

Even after using `useImg` , the image was loading in `background-image:url('')`

**and**

Documentation update needed , for a change from `imageLoaderConfig.setCacheDirectory` to `imageLoaderConfig.setCacheDirectoryName`

**Comment by ihadeed** [comment]
@uzumakinaruto123 I'm confused here. The error message indicates that that app tried fetching the URL `file:///android_asset/www/taken` but you're saying the image url was `file:///data/user/0/com.ionic.test/cache/ioniccache/63212651`. 

Can you provide me with steps to reproduce this issue? Maybe create a new issue if it's not related to the Firebase problem that @dmastag is having.

Also, thanks for pointing the other 2 issues out.

**Comment by uzumakinaruto123** [comment]
Sorry for confusing  :p   Actually , I was getting that error in console. I just thought it would be helpfull to mention. Actual url was the later one.  After using useImg as you mentioned on other issue , error does not appear anymore.  @dmastag  seems to have permission issues on firebase side.
