### ISSUE TITLE
useImg does not work

### ISSUE THREAD

**Issue by uzumakinaruto123** [zyramedia/ionic-image-loader#7]
From #4    ,

even after using `useImg`  , image loads as background.

if height and width are set to 100% image does not show up.

It needs style `height=250px` and `width="250px" `. Image is loading correctly.

Now , anyhow it loads in background + it will not show up unless width and height are specified in pixels.

**Comment by ihadeed** [comment]
Hey,

Try using `[useImg]="true"` instead of just `useImg`. That should work.

I will fix this soon so you can just type `useImg`. 

Thanks for pointing this out.

**Comment by uzumakinaruto123** [comment]
That worked  Can be closed , from my side. Thanks again for the great plugin.

**Comment by ihadeed** [comment]
I'll keep this open till we can just use `useImg` without adding `='true'`.
