### ISSUE TITLE
Enhancement : Usage for tags other than <img-loader> (ion-avatar,ion-thumbnail , div etc.)

### ISSUE THREAD

**Issue by uzumakinaruto123** [zyramedia/ionic-image-loader#8]
Can this be used with tags like `ion-avatar` , `<div>` etc.  ? If not , can this be considered as enhancement ?

**Comment by ihadeed** [comment]
Yes. This can replace `ion-avatar` and the others. Sometimes you might have to set `useImg='true'` to get it to work properly.
