### ISSUE TITLE
Not working on dynamic image urls

### ISSUE THREAD

**Issue by dmastag** [zyramedia/ionic-image-loader#9]
Hi ,

So I was scratching my head on the following until some debugging made me realize that the file was not stored at all or can't be shown for the below.

```<img-loader [useImg]="true" src="http://placehold.it/1200x960"></img-loader>```

Curious how to fix that.

**Comment by ihadeed** [comment]
There isn't a way at the moment to fix that. I can add an attribute `cache` that you can set to `false` to disable the caching feature and let the plugin load a new image every time you request that URL.

The plugin caches images based on their URLs and not the content. The only way to get around this now is to add a random string to the url. Example:

```html
<img-loader [src]="imageSrc"></img-loader>
```

```typescript
this.imageSrc = 'http://placehold.it/1200x960?v=' + Date.now();
```

**Comment by XPanniX** [comment]
Regarding your answer above I have to following code to display a users profile picture:
```
<img-loader [src]="user.picture.url"></img-loader>
```
This works fine, but when the user uploads a new profile picture I do the following:
```
self.user.picture.url = newProfilePicUrl;
```
Which is a different URL than before but the picture doesn't change.

So is there a bug in my code or in your module?

**Comment by ihadeed** [comment]
@XPanniX It's a missing feature wit the module. It only processes the initial value you provide, and doesn't handle next values. I will open a separate issue to track this.

**Comment by XPanniX** [comment]
Great! 
Any idea for a temporary workaround?

**Comment by ihadeed** [comment]
@XPanniX I will be submitting a fix soon for this.

But for now, the following should work if you aren't using the `img` tag (`useImg` isnt set to true):

```angular2html
<img-loader [src]="imagePath" #imgLoader></img-loader>
```

```typescript
@ViewChild('imgLoader') imgLoader: any;

// call this after changing the image src
this.imgLoader.ngOnInit();
```

**Comment by sergiomedinavalentin** [comment]
This solution works correctly, but I think that this  funcionality is very important for this module. Good job!

**Comment by ihadeed** [comment]
Regarding the initial issue here (dynamic URLs): I added a new attribute that disables caching. You can add `noCache` attribute or `[cache]="false"` to disable caching.

And in regards to handling `src` changes it's fixed too, now it will change the image whenever `src` attribute value changes.
